/** @file viewMenuHelp.java
 * @brief Aquesta classe és la view de ajuda al usuari.
 *
 * Els imports que utilitza són:
 *     - import java.awt.Color
 *     - import java.awt.Dimension
 *     - import java.awt.Frame
 *
 * @author Adrià Ventura i Herce
 */
package Presentation;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;

/*
 * Classe viewMenuHelp
 */

/** @class viewMenuHelp
 *  @brief Aquest és la view de ajuda al usuari.
 *
 *  @author Adria Ventura i Herce
 */
public class viewMenuHelp extends javax.swing.JFrame {
    /** @brief Instància del controlador de persistentació, inicialitzada al crear el controlador de presentació.*/
    private final CtrlPresentation ctrlPresentation;
    /** @brief Posició X del ratolí.*/
    private int xMouse;
    /** @brief Posició Y del ratolí.*/
    private int yMouse;
    
    /** @brief Creadora per defecte de viewMenuHelp.
     * 
     * @param cP És el controlador de presentació.
     * 
     * \pre <em>Cert.</em>
     * \post Ha creat una instància de viewMenuHelp.
     */
    public viewMenuHelp(CtrlPresentation cP) {
        this.setUndecorated(true);
        
        ctrlPresentation = cP;
        initComponents();
        
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        
        this.setSize(new Dimension(500, 300));
        this.setResizable(false);
        
        panelMenuHelp.setBorder(new RoundedBorder(50));
        editorPaneHelp.setContentType("text/html");
        editorPaneHelp.setText(
            "<font face= 'Book Antiqua' style='font-size:15px'>EL COMPRESSOR</font><br>" +
            "<i>Aquest és el compressor fet pel grup 21.1 pel </i>" +
            "<i>projecte de PROP del Q1 del 2019/20. </i>" +
            "<i>Serveix per comprimir carpetes, arxius de text </i>" +
            "<i>.txt i imatges .ppm.<br>" +
            "</n>Per poder utilitzar-lo apreta Comença i </i>" +
            "<i>escolleix l'acció que vulguis realitzar.</i>"
        );
        editorPaneHelp.setEditable(false);
    }
    
    /** @brief Fa "visibles" els objectes del Form corresponent.
     * 
     * \pre <em>Cert.</em>
     * \post Ha fet "visible" els objectes del Form corresponent
     */
    public void makeVisible() {
        editorPaneHelp.setEnabled(true);
        labelBack.setEnabled(true);
        labelCrown.setEnabled(true);
        labelExit.setEnabled(true);
        labelMinimize.setEnabled(true);
        panelMenuHelp.setEnabled(true);
    }
    
    /** @brief Fa "invisibles" els objectes del Form corresponent.
     * 
     * \pre <em>Cert.</em>
     * \post Ha fet "invisibles" els objectes del Form corresponent
     */
    public void makeInvisible() {
        editorPaneHelp.setEnabled(false);
        labelBack.setEnabled(false);
        labelCrown.setEnabled(false);
        labelExit.setEnabled(false);
        labelMinimize.setEnabled(false);
        panelMenuHelp.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuHelp = new javax.swing.JPanel();
        labelExit = new javax.swing.JLabel();
        labelMinimize = new javax.swing.JLabel();
        labelCrown = new javax.swing.JLabel();
        labelBack = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editorPaneHelp = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenuHelp.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuHelp.setOpaque(false);
        panelMenuHelp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMenuHelpMouseDragged(evt);
            }
        });
        panelMenuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMenuHelpMousePressed(evt);
            }
        });

        labelExit.setBackground(new java.awt.Color(255, 255, 255));
        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SortirMitjana.png"))); // NOI18N
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        labelMinimize.setBackground(new java.awt.Color(255, 255, 255));
        labelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MinimitzarMitjana.png"))); // NOI18N
        labelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeMouseClicked(evt);
            }
        });

        labelCrown.setBackground(new java.awt.Color(255, 255, 255));
        labelCrown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/the_crownMitjana.png"))); // NOI18N

        labelBack.setBackground(new java.awt.Color(255, 255, 255));
        labelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/EndarrereMitjana.png"))); // NOI18N
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(editorPaneHelp);

        javax.swing.GroupLayout panelMenuHelpLayout = new javax.swing.GroupLayout(panelMenuHelp);
        panelMenuHelp.setLayout(panelMenuHelpLayout);
        panelMenuHelpLayout.setHorizontalGroup(
            panelMenuHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuHelpLayout.createSequentialGroup()
                        .addComponent(labelCrown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMinimize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExit))
                    .addGroup(panelMenuHelpLayout.createSequentialGroup()
                        .addComponent(labelBack)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMenuHelpLayout.setVerticalGroup(
            panelMenuHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMinimize)
                    .addGroup(panelMenuHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelExit)
                        .addComponent(labelCrown)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenuHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenuHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** @brief Tanca el form.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post El form es tanca.
     */
    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        ctrlPresentation.exit();
    }//GEN-LAST:event_labelExitMouseClicked

    /** @brief Minimitza el form.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post El form s'ha minimitzat.
     */
    private void labelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_labelMinimizeMouseClicked

    /** @brief Canvi de form de ajuda a form de main menú.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post Ha canviat del form de ajuda a form de main menú.
     */
    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        ctrlPresentation.syncViewMH_to_viewMM();
    }//GEN-LAST:event_labelBackMouseClicked

    /** @brief Canvi de posició del form.
     * 
     * @param evt S'utilitza per saber la posició relativa del ratolí.
     * 
     * \pre <em>Cert.</em>
     * \post Canvia la posició relativa del form a on ha arrossegat el ratolí.
     */
    private void panelMenuHelpMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuHelpMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelMenuHelpMouseDragged

    /** @brief Iniciar posició relativa del form a les variables.
     * 
     * @param evt S'utilitza per saber la posició relativa del ratolí.
     * 
     * \pre <em>Cert.</em>
     * \post Ha iniciat la posició relativa del form a les dos variables 2D.
     */
    private void panelMenuHelpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuHelpMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelMenuHelpMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editorPaneHelp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelCrown;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelMinimize;
    private javax.swing.JPanel panelMenuHelp;
    // End of variables declaration//GEN-END:variables
}
