/** @file viewActions.java
 *  @brief Aquesta classe és la view de les accions que podem realitzar.
 *
 * Els imports que utilitza són:
 *     - import java.awt.Color
 *     - import java.awt.Dimension
 *     - import java.awt.Frame
 *
 * @author Adrià Ventura i Herce
 */

package Presentation;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;

/*
 * viewActions
 */

/** @class viewActions
 *  @brief Aquest és la view de les accions que podem realitzar.
 *
 *  @author Adria Ventura i Herce
 */
public class viewActions extends javax.swing.JFrame {
    /** @brief Instància del controlador de persistentació, inicialitzada al crear el controlador de presentació.*/
    private final CtrlPresentation ctrlPresentation;
    /** @brief Posició X del ratolí.*/
    private int xMouse;
    /** @brief Posició Y del ratolí.*/
    private int yMouse;
    
    /** @brief Creadora per defecte de la viewActions.
     * 
     * @param cP Es el controlador de presentació.
     * 
     * \pre <em>Cert.</em>
     * \post Ha creat una instància de viewActions.
     */
    public viewActions(CtrlPresentation cP) {
        this.setUndecorated(true);
        
        ctrlPresentation = cP;
        
        initComponents();
        
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        
        this.setSize(new Dimension(500, 300));
        this.setResizable(false);
        
        panelAccions.setBorder(new RoundedBorder(50));
        btnComprimir.setBorder(new RoundedBorder(40));
        btnComprimir.setContentAreaFilled(false);
        btnDescomprimir.setBorder(new RoundedBorder(40));
        btnDescomprimir.setContentAreaFilled(false);
        
    }
    
    /** @brief Fa "visibles" els objectes del Form corresponent.
     * 
     * \pre <em>Cert.</em>
     * \post Ha fet "visible" els objectes del Form corresponent.
     */
    public void makeVisible() {
        //Activa Panel
        panelAccions.setEnabled(true);
        
        //Activa Button
        btnComprimir.setEnabled(true);
        btnDescomprimir.setEnabled(true);
                
        //Activa label
        labelTitol.setEnabled(true);
        labelBack.setEnabled(true);
    }
    
    /** @brief Fa "invisibles" els objectes del Form corresponent.
     * 
     * \pre <em>Cert.</em>
     * \post Ha fet "invisibles" els objectes del Form corresponent
     */
    public void makeInvisible() {
        
        //Desactiva Button
        btnComprimir.setEnabled(false);
        btnDescomprimir.setEnabled(false);
                
        //Desactiva label
        labelTitol.setEnabled(false);
        labelBack.setEnabled(false);
        
        //Desactiva Panel
        panelAccions.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAccions = new javax.swing.JPanel();
        btnComprimir = new javax.swing.JButton();
        btnDescomprimir = new javax.swing.JButton();
        labelTitol = new javax.swing.JLabel();
        labelBack = new javax.swing.JLabel();
        labelMinimize = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        labelCrown = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAccions.setBackground(new java.awt.Color(255, 255, 255));
        panelAccions.setForeground(new java.awt.Color(255, 255, 255));
        panelAccions.setOpaque(false);
        panelAccions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelAccionsMouseDragged(evt);
            }
        });
        panelAccions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelAccionsMousePressed(evt);
            }
        });

        btnComprimir.setBackground(new java.awt.Color(255, 255, 255));
        btnComprimir.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnComprimir.setForeground(new java.awt.Color(0, 0, 0));
        btnComprimir.setText("Comprimir");
        btnComprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnComprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprimirActionPerformed(evt);
            }
        });

        btnDescomprimir.setBackground(new java.awt.Color(255, 255, 255));
        btnDescomprimir.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnDescomprimir.setForeground(new java.awt.Color(0, 0, 0));
        btnDescomprimir.setText("Descomprimir");
        btnDescomprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescomprimirActionPerformed(evt);
            }
        });

        labelTitol.setBackground(new java.awt.Color(255, 255, 255));
        labelTitol.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        labelTitol.setForeground(new java.awt.Color(0, 0, 0));
        labelTitol.setText("Selecciona l'acció que vulguis realitzar:");
        labelTitol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelBack.setBackground(new java.awt.Color(255, 255, 255));
        labelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/EndarrereMitjana.png"))); // NOI18N
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
        });

        labelMinimize.setBackground(new java.awt.Color(255, 255, 255));
        labelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MinimitzarMitjana.png"))); // NOI18N
        labelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeMouseClicked(evt);
            }
        });

        labelExit.setBackground(new java.awt.Color(255, 255, 255));
        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SortirMitjana.png"))); // NOI18N
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        labelCrown.setBackground(new java.awt.Color(255, 255, 255));
        labelCrown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/the_crownMitjana.png"))); // NOI18N

        javax.swing.GroupLayout panelAccionsLayout = new javax.swing.GroupLayout(panelAccions);
        panelAccions.setLayout(panelAccionsLayout);
        panelAccionsLayout.setHorizontalGroup(
            panelAccionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionsLayout.createSequentialGroup()
                .addGroup(panelAccionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAccionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelCrown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMinimize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelExit))
                    .addGroup(panelAccionsLayout.createSequentialGroup()
                        .addGroup(panelAccionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnComprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAccionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAccionsLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(labelBack))
                                .addGroup(panelAccionsLayout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(btnDescomprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelAccionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAccionsLayout.setVerticalGroup(
            panelAccionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAccionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelExit)
                    .addComponent(labelMinimize)
                    .addComponent(labelCrown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTitol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(btnComprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDescomprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(labelBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAccions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAccions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** @brief Canvi de form de Accions a form de Descompressió.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post Ha canviat del form de Accions al form de Descompressió.
     */
    private void btnDescomprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescomprimirActionPerformed
        ctrlPresentation.syncViewA_to_viewFSD();
    }//GEN-LAST:event_btnDescomprimirActionPerformed

    /** @brief Canvi de form de Accions a form de Compressió.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post Ha canviat del form de Accions al form de Compressió.
     */
    private void btnComprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprimirActionPerformed
        ctrlPresentation.syncViewA_to_viewCO();
    }//GEN-LAST:event_btnComprimirActionPerformed

    /** @brief Canvi de form de Accions a form de Menú Prinipal.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post Ha canviat del form de Accions al form de Menú Prinipal.
     */   
    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        ctrlPresentation.syncViewA_to_viewMM();
    }//GEN-LAST:event_labelBackMouseClicked

    /** @brief Minimitza el form.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post El form s'ha minimitzat.
     */ 
    private void labelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_labelMinimizeMouseClicked

    /** @brief Tanca el form.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post El form es tanca.
     */ 
    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        ctrlPresentation.exit();
    }//GEN-LAST:event_labelExitMouseClicked

    /** @brief Canvi de posició del form.
     * 
     * @param evt S'utilitza per saber la posició relativa del ratolí.
     * 
     * \pre <em>Cert.</em>
     * \post Canvia la posició relativa del form a on ha arrossegat el ratolí.
     */
    private void panelAccionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAccionsMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelAccionsMouseDragged

    /** @brief Iniciar posició relativa del form a les variables.
     * 
     * @param evt S'utilitza per saber la posició relativa del ratolí.
     * 
     * \pre <em>Cert.</em>
     * \post Ha iniciat la posició relativa del form a les dos variables 2D.
     */
    private void panelAccionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAccionsMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelAccionsMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprimir;
    private javax.swing.JButton btnDescomprimir;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelCrown;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelMinimize;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JPanel panelAccions;
    // End of variables declaration//GEN-END:variables
}
