/** @file viewCompressionOptions.java
 * @brief Aquesta classe és la view de les opcions de compressió.
 *
 * Els imports que utilitza són:
 *     - import java.awt.Color
 *     - import java.awt.Dimension
 *     - import java.awt.Frame
 *
 * @author Adrià Ventura i Herce
 */
package Presentation;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;

/*
 * Classe viewCompressionOptions
 */

/** @class viewCompressionOptions
 * @brief Aquest és la view de les opcions de compressió.
 *
 * @author Adria Ventura i Herce
 */
public class viewCompressionOptions extends javax.swing.JFrame {
    /** @brief Instància del controlador de persistentació, inicialitzada al crear el controlador de presentació.*/
    private final CtrlPresentation ctrlPresentation;
    /** @brief Posició X del ratolí.*/
    private int xMouse;
    /** @brief Posició Y del ratolí.*/
    private int yMouse;
    
    /** @brief Creadora per defecte de viewCompressionOptions.
     * 
     * @param cP Es el controlador de presentació.
     * 
     * \pre <em>Cert.</em>
     * \post Ha creat una instància de viewCompressionOptions.
     */
    public viewCompressionOptions(CtrlPresentation cP) {
        this.setUndecorated(true);
        
        ctrlPresentation = cP;
        
        initComponents();
        
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        
        this.setSize(new Dimension(500, 300));
        this.setResizable(false);
        
        panelComOpt.setBorder(new RoundedBorder(50));
        btnAutomatic.setBorder(new RoundedBorder(40));
        btnAutomatic.setContentAreaFilled(false);
        btnManual.setBorder(new RoundedBorder(40));
        btnManual.setContentAreaFilled(false);   
    }
    
    /** @brief Fa "visibles" els objectes del Form corresponent.
     * 
     * \pre <em>Cert.</em>
     * \post Ha fet "visible" els objectes del Form corresponent
     */
    public void makeVisible() {
        //Activa Panel
        panelComOpt.setEnabled(true);
        
        //Activa Buttons
        btnAutomatic.setEnabled(true);
        btnManual.setEnabled(true);
        labelBack.setEnabled(true);
    }
    
    /** @brief Fa "invisibles" els objectes del Form corresponent.
     * 
     * \pre <em>Cert.</em>
     * \post Ha fet "invisibles" els objectes del Form corresponent
     */
    public void makeInvisible() {
        //Desactiva Buttons
        btnAutomatic.setEnabled(false);
        btnManual.setEnabled(false);
        labelBack.setEnabled(false);
        
        //Desactiva Panel
        panelComOpt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelComOpt = new javax.swing.JPanel();
        btnManual = new javax.swing.JButton();
        btnAutomatic = new javax.swing.JButton();
        labelBack = new javax.swing.JLabel();
        labelMinimize = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        labelCrown = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelComOpt.setBackground(new java.awt.Color(255, 255, 255));
        panelComOpt.setOpaque(false);
        panelComOpt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelComOptMouseDragged(evt);
            }
        });
        panelComOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelComOptMousePressed(evt);
            }
        });

        btnManual.setBackground(new java.awt.Color(255, 255, 255));
        btnManual.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnManual.setForeground(new java.awt.Color(0, 0, 0));
        btnManual.setText("Manual");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });

        btnAutomatic.setBackground(new java.awt.Color(255, 255, 255));
        btnAutomatic.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnAutomatic.setForeground(new java.awt.Color(0, 0, 0));
        btnAutomatic.setText("Automàtic");
        btnAutomatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticActionPerformed(evt);
            }
        });

        labelBack.setBackground(new java.awt.Color(255, 255, 255));
        labelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/EndarrereMitjana.png"))); // NOI18N
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
        });

        labelMinimize.setBackground(new java.awt.Color(255, 255, 255));
        labelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MinimitzarMitjana.png"))); // NOI18N
        labelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeMouseClicked(evt);
            }
        });

        labelExit.setBackground(new java.awt.Color(255, 255, 255));
        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SortirMitjana.png"))); // NOI18N
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        labelCrown.setBackground(new java.awt.Color(255, 255, 255));
        labelCrown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/the_crownMitjana.png"))); // NOI18N

        javax.swing.GroupLayout panelComOptLayout = new javax.swing.GroupLayout(panelComOpt);
        panelComOpt.setLayout(panelComOptLayout);
        panelComOptLayout.setHorizontalGroup(
            panelComOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComOptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComOptLayout.createSequentialGroup()
                        .addGroup(panelComOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComOptLayout.createSequentialGroup()
                                .addComponent(labelBack)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComOptLayout.createSequentialGroup()
                                .addComponent(labelCrown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelMinimize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelExit)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComOptLayout.createSequentialGroup()
                        .addGap(0, 158, Short.MAX_VALUE)
                        .addGroup(panelComOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAutomatic, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(btnManual, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addContainerGap(152, Short.MAX_VALUE))))
        );
        panelComOptLayout.setVerticalGroup(
            panelComOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComOptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelComOptLayout.createSequentialGroup()
                        .addComponent(labelCrown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelBack))
                    .addGroup(panelComOptLayout.createSequentialGroup()
                        .addGroup(panelComOptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelExit)
                            .addComponent(labelMinimize))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btnAutomatic, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelComOpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelComOpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** @brief Canvi de form de les opcions de compressió al form de seleccio d'algorismes.
     * 
     * @param evt
     * 
     * \pre S'ha seleccionat un algorisme.
     * \post Ha canviat del form de les opcions de compressió al form de seleccio d'algorismes.
     */
    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        if (ctrlPresentation.getAlgorithmType().equals("")) ctrlPresentation.setAlgorithmType("");
        ctrlPresentation.syncViewCO_to_viewAlg();
    }//GEN-LAST:event_btnManualActionPerformed

    /** @brief Canvi de form de les opcions de compressió al form de compressió automàtica.
     * 
     * @param evt
     * 
     * \pre S'ha seleccionat un algorisme.
     * \post Ha canviat del form de les opcions de compressió al form de compressió automàtica.
     */
    private void btnAutomaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticActionPerformed
        ctrlPresentation.syncViewCO_to_viewFSCA();
    }//GEN-LAST:event_btnAutomaticActionPerformed

    /** @brief Canvi de form del selecctor d'algoritmes a form de opcions de compressió.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post Ha canviat del form del selecctor d'algoritmes a form de opcions de compressió.
     */
    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        ctrlPresentation.syncViewCO_to_viewA();
    }//GEN-LAST:event_labelBackMouseClicked

    /** @brief Minimitza el form.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post El form s'ha minimitzat.
     */
    private void labelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_labelMinimizeMouseClicked

    /** @brief Tanca el form.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post El form es tanca.
     */
    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        ctrlPresentation.exit();
    }//GEN-LAST:event_labelExitMouseClicked

    /** @brief Canvi de posició del form.
     * 
     * @param evt S'utilitza per saber la posició relativa del ratolí.
     * 
     * \pre <em>Cert.</em>
     * \post Canvia la posició relativa del form a on ha arrossegat el ratolí.
     */
    private void panelComOptMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComOptMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelComOptMouseDragged

    /** @brief Iniciar posició relativa del form a les variables.
     * 
     * @param evt S'utilitza per saver la posició relativa del ratolí.
     * 
     * \pre <em>Cert.</em>
     * \post Ha iniciat la posició relativa del form a les dos variables 2D.
     */
    private void panelComOptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComOptMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelComOptMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutomatic;
    private javax.swing.JButton btnManual;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelCrown;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelMinimize;
    private javax.swing.JPanel panelComOpt;
    // End of variables declaration//GEN-END:variables
}
