/** @file viewMainMenu.java
 * @brief Aquesta classe és la view del menú principal del programa.
 *
 * Els imports que utilitza són:
 *     - import java.awt.Color
 *     - import java.awt.Dimension
 *     - import java.awt.Frame
 *     - import java.io.IOException
 *     - import java.util.logging.Level
 *     - import java.util.logging.Logger
 *     - import javax.swing.JPanel
 *
 * @author Adrià Ventura i Herce
 */
package Presentation;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/*
 * Classe viewMainMenu
 */

/** @class viewMainMenu
 *  @brief Aquest és la view del menú principal del programa.
 *
 *  @author Adria Ventura i Herce
 */
public class viewMainMenu extends javax.swing.JFrame {
    /** @brief Instància del controlador de persistentació, inicialitzada al crear el controlador de presentació.*/
    private final CtrlPresentation ctrlPresentation;
    /** @brief Posició X del ratolí.*/
    private int xMouse;
    /** @brief Posició Y del ratolí.*/
    private int yMouse;
    
    /** @brief Creadora per defecte de viewMainMenu.
     * 
     * @param cP Es el controlador de presentació.
     * 
     * \pre <em>Cert.</em>
     * \post Ha creat una instància de viewMainMenu.
     */
    public viewMainMenu(CtrlPresentation cP) {
        this.setUndecorated(true);
        
        ctrlPresentation = cP;
        initComponents();
        
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        
        this.setSize(new Dimension(500, 300));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        menuPanel.setBorder(new RoundedBorder(50));
        btnComença.setBorder(new RoundedBorder(40));
        btnComença.setContentAreaFilled(false);
        btnEstadistiques.setBorder(new RoundedBorder(40));
        btnEstadistiques.setContentAreaFilled(false);
    }
    
    /** @brief Fa "visibles" els objectes del Form corresponent.
     * 
     * \pre <em>Cert.</em>
     * \post Ha fet "visible" els objectes del Form corresponent
     */
    public void makeVisible() {
        btnComença.setEnabled(true);
        btnEstadistiques.setEnabled(true);
        labelTitol.setEnabled(true);
        labelExit.setEnabled(true);
        labelHelp.setEnabled(true);
        menuPanel.setEnabled(true);
    }
    
    /** @brief Fa "invisibles" els objectes del Form corresponent.
     * 
     * \pre <em>Cert.</em>
     * \post Ha fet "invisibles" els objectes del Form corresponent
     */
    public void makeInvisible() {
        btnComença.setEnabled(false);
        btnEstadistiques.setEnabled(false);
        labelTitol.setEnabled(false);
        labelExit.setEnabled(false);
        labelHelp.setEnabled(false);
        menuPanel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new JPanel();
        labelTitol = new javax.swing.JLabel();
        btnComença = new javax.swing.JButton();
        btnEstadistiques = new javax.swing.JButton();
        labelExit = new javax.swing.JLabel();
        labelHelp = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();
        labelMinimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setOpaque(false);
        menuPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuPanelMouseDragged(evt);
            }
        });
        menuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuPanelMousePressed(evt);
            }
        });

        labelTitol.setBackground(new java.awt.Color(255, 255, 255));
        labelTitol.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        labelTitol.setForeground(new java.awt.Color(0, 0, 0));
        labelTitol.setText("EL COMPRESSOR");

        btnComença.setBackground(new java.awt.Color(255, 255, 255));
        btnComença.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnComença.setForeground(new java.awt.Color(0, 0, 0));
        btnComença.setText("Comença");
        btnComença.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComençaActionPerformed(evt);
            }
        });

        btnEstadistiques.setBackground(new java.awt.Color(255, 255, 255));
        btnEstadistiques.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnEstadistiques.setForeground(new java.awt.Color(0, 0, 0));
        btnEstadistiques.setText("Estadístiques");
        btnEstadistiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadistiquesActionPerformed(evt);
            }
        });

        labelExit.setBackground(new java.awt.Color(255, 255, 255));
        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SortirMitjana.png"))); // NOI18N
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        labelHelp.setBackground(new java.awt.Color(255, 255, 255));
        labelHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/AjudaMitjana.png"))); // NOI18N
        labelHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHelpMouseClicked(evt);
            }
        });

        labelIcon.setBackground(new java.awt.Color(255, 255, 255));
        labelIcon.setForeground(new java.awt.Color(255, 255, 255));
        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/the_crown.png"))); // NOI18N

        labelMinimize.setBackground(new java.awt.Color(255, 255, 255));
        labelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MinimitzarMitjana.png"))); // NOI18N
        labelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelTitol)
                    .addComponent(btnComença, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstadistiques, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(labelIcon))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelExit)
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelExit)
                    .addComponent(labelMinimize)
                    .addComponent(labelHelp))
                .addGap(7, 7, 7)
                .addComponent(labelIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComença)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadistiques)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** @brief Canvi de form del menú principal a form de opcions de accions.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post Ha canviat del form del menú principal a form de opcions de accions.
     */
    private void btnComençaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComençaActionPerformed
        ctrlPresentation.syncViewMM_to_viewA();
    }//GEN-LAST:event_btnComençaActionPerformed

    /** @brief Tanca el form.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post El form es tanca.
     */
    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        ctrlPresentation.exit();
    }//GEN-LAST:event_labelExitMouseClicked

    /** @brief Canvi de form del menú principal a form de ajuda.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post Ha canviat del form del menú principal a form de ajuda.
     */
    private void labelHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHelpMouseClicked
        ctrlPresentation.syncViewMM_to_viewMH();
    }//GEN-LAST:event_labelHelpMouseClicked

    /** @brief Canvi de form del menú principal a form de estadístiques.
     * 
     * @param evt
     * 
     * \pre <em>Cert.</em>
     * \post Ha canviat del form del menú principal a form de estadístiques.
     */
    private void btnEstadistiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadistiquesActionPerformed
        try {
            ctrlPresentation.syncViewMM_to_viewS();
        } catch (IOException ex) {
            Logger.getLogger(viewMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEstadistiquesActionPerformed

    /** @brief Minimitza el form.
     * 
     * @param evt 
     * 
     * \pre <em>Cert.</em>
     * \post El form s'ha minimitzat.
     */
    private void labelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_labelMinimizeMouseClicked

    /** @brief Canvi de posició del form.
     * 
     * @param evt S'utilitza per saber la posició relativa del ratolí.
     * 
     * \pre <em>Cert.</em>
     * \post Canvia la posició relativa del form a on ha arrossegat el ratolí.
     */
    private void menuPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_menuPanelMouseDragged

    /** @brief Iniciar posició relativa del form a les variables.
     * 
     * @param evt S'utilitza per saber la posició relativa del ratolí.
     * 
     * \pre <em>Cert.</em>
     * \post Ha iniciat la posició relativa del form a les dos variables 2D.
     */
    private void menuPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_menuPanelMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComença;
    private javax.swing.JButton btnEstadistiques;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelHelp;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelMinimize;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
